//GET http://127.0.0.1:8080/search?title=test
//Accept: application/json

GET http://127.0.0.1:8080/search?title=yellowstone
Accept: application/json

GET http://127.0.0.1:8080/search?title=wednesday
Accept: application/json

GET http://127.0.0.1:8080/search?title=star wars
Accept: application/json

GET http://127.0.0.1:8080/search?title=star-wars
Accept: application/json
